packages:
  - "config/"
  - "packages/*"
  - "playgrounds/*"
  - "docs/"

catalog:
  "typescript": "5.7.3" # https://www.npmjs.com/package/typescript
  "vite": "6.1.1" # https://www.npmjs.com/package/vite
  # == storybook https://storybook.js.org/ ==
  "@chromatic-com/storybook": "^3.2.2"
  "@storybook/addon-essentials": "8.4.6"
  "@storybook/addon-interactions": "8.4.6"
  "@storybook/addon-links": "8.4.6"
  "@storybook/addon-onboarding": "8.4.6"
  "@storybook/blocks": "8.4.6"
  "@storybook/manager-api": "8.4.6"
  "@storybook/test": "8.4.6"
  "@storybook/theming": "8.4.6"
  "storybook": "8.4.6" # https://www.npmjs.com/package/storybook
  "storybook-dark-mode": "^4.0.2"