packages:
  - "config/"
  - "packages/*"
  - "playgrounds/*"
  - "docs/"

catalog:
  "typescript": "5.6.3" # https://www.typescriptlang.org/
  "vite": "6.0.1" # https://vitejs.dev/
  # == storybook https://storybook.js.org/ ==
  "@chromatic-com/storybook": "^3.2.2"
  "@storybook/addon-essentials": "8.4.6"
  "@storybook/addon-interactions": "8.4.6"
  "@storybook/addon-links": "8.4.6"
  "@storybook/addon-onboarding": "8.4.6"
  "@storybook/blocks": "8.4.6"
  "@storybook/manager-api": "8.4.6"
  "@storybook/test": "8.4.6"
  "@storybook/theming": "8.4.6"
  "storybook": "8.4.6"
  "storybook-dark-mode": "^4.0.2"