/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangTestRouteRouteImport } from './routes/$lang/test/route'
import { Route as LangDocsRouteRouteImport } from './routes/$lang/docs/route'
import { Route as LangDocsIndexRouteImport } from './routes/$lang/docs/index'
import { Route as LangDocsFrameworkRouteRouteImport } from './routes/$lang/docs/$framework/route'
import { Route as LangDocsFrameworkOverviewRouteImport } from './routes/$lang/docs/$framework/overview'
import { Route as LangDocsFrameworkInstallationRouteImport } from './routes/$lang/docs/$framework/installation'
import { Route as LangDocsFrameworkComponentsUlRouteImport } from './routes/$lang/docs/$framework/components/ul'
import { Route as LangDocsFrameworkComponentsSelectRouteImport } from './routes/$lang/docs/$framework/components/select'
import { Route as LangDocsFrameworkComponentsPagersRouteImport } from './routes/$lang/docs/$framework/components/pagers'
import { Route as LangDocsFrameworkComponentsPagerRouteImport } from './routes/$lang/docs/$framework/components/pager'
import { Route as LangDocsFrameworkComponentsOptionRouteImport } from './routes/$lang/docs/$framework/components/option'
import { Route as LangDocsFrameworkComponentsNavaccordionRouteImport } from './routes/$lang/docs/$framework/components/navaccordion'
import { Route as LangDocsFrameworkComponentsLiRouteImport } from './routes/$lang/docs/$framework/components/li'
import { Route as LangDocsFrameworkComponentsInputRouteImport } from './routes/$lang/docs/$framework/components/input'
import { Route as LangDocsFrameworkComponentsHeaderRouteImport } from './routes/$lang/docs/$framework/components/header'
import { Route as LangDocsFrameworkComponentsH6RouteImport } from './routes/$lang/docs/$framework/components/h6'
import { Route as LangDocsFrameworkComponentsH5RouteImport } from './routes/$lang/docs/$framework/components/h5'
import { Route as LangDocsFrameworkComponentsH4RouteImport } from './routes/$lang/docs/$framework/components/h4'
import { Route as LangDocsFrameworkComponentsH3RouteImport } from './routes/$lang/docs/$framework/components/h3'
import { Route as LangDocsFrameworkComponentsH2RouteImport } from './routes/$lang/docs/$framework/components/h2'
import { Route as LangDocsFrameworkComponentsH1RouteImport } from './routes/$lang/docs/$framework/components/h1'
import { Route as LangDocsFrameworkComponentsErrorRouteImport } from './routes/$lang/docs/$framework/components/error'
import { Route as LangDocsFrameworkComponentsDividerRouteImport } from './routes/$lang/docs/$framework/components/divider'
import { Route as LangDocsFrameworkComponentsCodeblockRouteImport } from './routes/$lang/docs/$framework/components/codeblock'
import { Route as LangDocsFrameworkComponentsButtonRouteImport } from './routes/$lang/docs/$framework/components/button'
import { Route as LangDocsFrameworkComponentsBreadcrumbRouteImport } from './routes/$lang/docs/$framework/components/breadcrumb'
import { Route as LangDocsFrameworkComponentsBadgeRouteImport } from './routes/$lang/docs/$framework/components/badge'
import { Route as LangDocsFrameworkComponentsAnchorRouteImport } from './routes/$lang/docs/$framework/components/anchor'
import { ServerRoute as ApiPageInfoServerRouteImport } from './routes/api/page-info'
import { ServerRoute as ApiHeartbeatServerRouteImport } from './routes/api/heartbeat'

const rootServerRouteImport = createServerRootRoute()

const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangTestRouteRoute = LangTestRouteRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangDocsRouteRoute = LangDocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangDocsIndexRoute = LangDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangDocsRouteRoute,
} as any)
const LangDocsFrameworkRouteRoute = LangDocsFrameworkRouteRouteImport.update({
  id: '/$framework',
  path: '/$framework',
  getParentRoute: () => LangDocsRouteRoute,
} as any)
const LangDocsFrameworkOverviewRoute =
  LangDocsFrameworkOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkInstallationRoute =
  LangDocsFrameworkInstallationRouteImport.update({
    id: '/installation',
    path: '/installation',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsUlRoute =
  LangDocsFrameworkComponentsUlRouteImport.update({
    id: '/components/ul',
    path: '/components/ul',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsSelectRoute =
  LangDocsFrameworkComponentsSelectRouteImport.update({
    id: '/components/select',
    path: '/components/select',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsPagersRoute =
  LangDocsFrameworkComponentsPagersRouteImport.update({
    id: '/components/pagers',
    path: '/components/pagers',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsPagerRoute =
  LangDocsFrameworkComponentsPagerRouteImport.update({
    id: '/components/pager',
    path: '/components/pager',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsOptionRoute =
  LangDocsFrameworkComponentsOptionRouteImport.update({
    id: '/components/option',
    path: '/components/option',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsNavaccordionRoute =
  LangDocsFrameworkComponentsNavaccordionRouteImport.update({
    id: '/components/navaccordion',
    path: '/components/navaccordion',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsLiRoute =
  LangDocsFrameworkComponentsLiRouteImport.update({
    id: '/components/li',
    path: '/components/li',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsInputRoute =
  LangDocsFrameworkComponentsInputRouteImport.update({
    id: '/components/input',
    path: '/components/input',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsHeaderRoute =
  LangDocsFrameworkComponentsHeaderRouteImport.update({
    id: '/components/header',
    path: '/components/header',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsH6Route =
  LangDocsFrameworkComponentsH6RouteImport.update({
    id: '/components/h6',
    path: '/components/h6',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsH5Route =
  LangDocsFrameworkComponentsH5RouteImport.update({
    id: '/components/h5',
    path: '/components/h5',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsH4Route =
  LangDocsFrameworkComponentsH4RouteImport.update({
    id: '/components/h4',
    path: '/components/h4',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsH3Route =
  LangDocsFrameworkComponentsH3RouteImport.update({
    id: '/components/h3',
    path: '/components/h3',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsH2Route =
  LangDocsFrameworkComponentsH2RouteImport.update({
    id: '/components/h2',
    path: '/components/h2',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsH1Route =
  LangDocsFrameworkComponentsH1RouteImport.update({
    id: '/components/h1',
    path: '/components/h1',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsErrorRoute =
  LangDocsFrameworkComponentsErrorRouteImport.update({
    id: '/components/error',
    path: '/components/error',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsDividerRoute =
  LangDocsFrameworkComponentsDividerRouteImport.update({
    id: '/components/divider',
    path: '/components/divider',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsCodeblockRoute =
  LangDocsFrameworkComponentsCodeblockRouteImport.update({
    id: '/components/codeblock',
    path: '/components/codeblock',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsButtonRoute =
  LangDocsFrameworkComponentsButtonRouteImport.update({
    id: '/components/button',
    path: '/components/button',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsBreadcrumbRoute =
  LangDocsFrameworkComponentsBreadcrumbRouteImport.update({
    id: '/components/breadcrumb',
    path: '/components/breadcrumb',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsBadgeRoute =
  LangDocsFrameworkComponentsBadgeRouteImport.update({
    id: '/components/badge',
    path: '/components/badge',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const LangDocsFrameworkComponentsAnchorRoute =
  LangDocsFrameworkComponentsAnchorRouteImport.update({
    id: '/components/anchor',
    path: '/components/anchor',
    getParentRoute: () => LangDocsFrameworkRouteRoute,
  } as any)
const ApiPageInfoServerRoute = ApiPageInfoServerRouteImport.update({
  id: '/api/page-info',
  path: '/api/page-info',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiHeartbeatServerRoute = ApiHeartbeatServerRouteImport.update({
  id: '/api/heartbeat',
  path: '/api/heartbeat',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/docs': typeof LangDocsRouteRouteWithChildren
  '/$lang/test': typeof LangTestRouteRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/docs/$framework': typeof LangDocsFrameworkRouteRouteWithChildren
  '/$lang/docs/': typeof LangDocsIndexRoute
  '/$lang/docs/$framework/installation': typeof LangDocsFrameworkInstallationRoute
  '/$lang/docs/$framework/overview': typeof LangDocsFrameworkOverviewRoute
  '/$lang/docs/$framework/components/anchor': typeof LangDocsFrameworkComponentsAnchorRoute
  '/$lang/docs/$framework/components/badge': typeof LangDocsFrameworkComponentsBadgeRoute
  '/$lang/docs/$framework/components/breadcrumb': typeof LangDocsFrameworkComponentsBreadcrumbRoute
  '/$lang/docs/$framework/components/button': typeof LangDocsFrameworkComponentsButtonRoute
  '/$lang/docs/$framework/components/codeblock': typeof LangDocsFrameworkComponentsCodeblockRoute
  '/$lang/docs/$framework/components/divider': typeof LangDocsFrameworkComponentsDividerRoute
  '/$lang/docs/$framework/components/error': typeof LangDocsFrameworkComponentsErrorRoute
  '/$lang/docs/$framework/components/h1': typeof LangDocsFrameworkComponentsH1Route
  '/$lang/docs/$framework/components/h2': typeof LangDocsFrameworkComponentsH2Route
  '/$lang/docs/$framework/components/h3': typeof LangDocsFrameworkComponentsH3Route
  '/$lang/docs/$framework/components/h4': typeof LangDocsFrameworkComponentsH4Route
  '/$lang/docs/$framework/components/h5': typeof LangDocsFrameworkComponentsH5Route
  '/$lang/docs/$framework/components/h6': typeof LangDocsFrameworkComponentsH6Route
  '/$lang/docs/$framework/components/header': typeof LangDocsFrameworkComponentsHeaderRoute
  '/$lang/docs/$framework/components/input': typeof LangDocsFrameworkComponentsInputRoute
  '/$lang/docs/$framework/components/li': typeof LangDocsFrameworkComponentsLiRoute
  '/$lang/docs/$framework/components/navaccordion': typeof LangDocsFrameworkComponentsNavaccordionRoute
  '/$lang/docs/$framework/components/option': typeof LangDocsFrameworkComponentsOptionRoute
  '/$lang/docs/$framework/components/pager': typeof LangDocsFrameworkComponentsPagerRoute
  '/$lang/docs/$framework/components/pagers': typeof LangDocsFrameworkComponentsPagersRoute
  '/$lang/docs/$framework/components/select': typeof LangDocsFrameworkComponentsSelectRoute
  '/$lang/docs/$framework/components/ul': typeof LangDocsFrameworkComponentsUlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/test': typeof LangTestRouteRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/docs/$framework': typeof LangDocsFrameworkRouteRouteWithChildren
  '/$lang/docs': typeof LangDocsIndexRoute
  '/$lang/docs/$framework/installation': typeof LangDocsFrameworkInstallationRoute
  '/$lang/docs/$framework/overview': typeof LangDocsFrameworkOverviewRoute
  '/$lang/docs/$framework/components/anchor': typeof LangDocsFrameworkComponentsAnchorRoute
  '/$lang/docs/$framework/components/badge': typeof LangDocsFrameworkComponentsBadgeRoute
  '/$lang/docs/$framework/components/breadcrumb': typeof LangDocsFrameworkComponentsBreadcrumbRoute
  '/$lang/docs/$framework/components/button': typeof LangDocsFrameworkComponentsButtonRoute
  '/$lang/docs/$framework/components/codeblock': typeof LangDocsFrameworkComponentsCodeblockRoute
  '/$lang/docs/$framework/components/divider': typeof LangDocsFrameworkComponentsDividerRoute
  '/$lang/docs/$framework/components/error': typeof LangDocsFrameworkComponentsErrorRoute
  '/$lang/docs/$framework/components/h1': typeof LangDocsFrameworkComponentsH1Route
  '/$lang/docs/$framework/components/h2': typeof LangDocsFrameworkComponentsH2Route
  '/$lang/docs/$framework/components/h3': typeof LangDocsFrameworkComponentsH3Route
  '/$lang/docs/$framework/components/h4': typeof LangDocsFrameworkComponentsH4Route
  '/$lang/docs/$framework/components/h5': typeof LangDocsFrameworkComponentsH5Route
  '/$lang/docs/$framework/components/h6': typeof LangDocsFrameworkComponentsH6Route
  '/$lang/docs/$framework/components/header': typeof LangDocsFrameworkComponentsHeaderRoute
  '/$lang/docs/$framework/components/input': typeof LangDocsFrameworkComponentsInputRoute
  '/$lang/docs/$framework/components/li': typeof LangDocsFrameworkComponentsLiRoute
  '/$lang/docs/$framework/components/navaccordion': typeof LangDocsFrameworkComponentsNavaccordionRoute
  '/$lang/docs/$framework/components/option': typeof LangDocsFrameworkComponentsOptionRoute
  '/$lang/docs/$framework/components/pager': typeof LangDocsFrameworkComponentsPagerRoute
  '/$lang/docs/$framework/components/pagers': typeof LangDocsFrameworkComponentsPagersRoute
  '/$lang/docs/$framework/components/select': typeof LangDocsFrameworkComponentsSelectRoute
  '/$lang/docs/$framework/components/ul': typeof LangDocsFrameworkComponentsUlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/docs': typeof LangDocsRouteRouteWithChildren
  '/$lang/test': typeof LangTestRouteRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/docs/$framework': typeof LangDocsFrameworkRouteRouteWithChildren
  '/$lang/docs/': typeof LangDocsIndexRoute
  '/$lang/docs/$framework/installation': typeof LangDocsFrameworkInstallationRoute
  '/$lang/docs/$framework/overview': typeof LangDocsFrameworkOverviewRoute
  '/$lang/docs/$framework/components/anchor': typeof LangDocsFrameworkComponentsAnchorRoute
  '/$lang/docs/$framework/components/badge': typeof LangDocsFrameworkComponentsBadgeRoute
  '/$lang/docs/$framework/components/breadcrumb': typeof LangDocsFrameworkComponentsBreadcrumbRoute
  '/$lang/docs/$framework/components/button': typeof LangDocsFrameworkComponentsButtonRoute
  '/$lang/docs/$framework/components/codeblock': typeof LangDocsFrameworkComponentsCodeblockRoute
  '/$lang/docs/$framework/components/divider': typeof LangDocsFrameworkComponentsDividerRoute
  '/$lang/docs/$framework/components/error': typeof LangDocsFrameworkComponentsErrorRoute
  '/$lang/docs/$framework/components/h1': typeof LangDocsFrameworkComponentsH1Route
  '/$lang/docs/$framework/components/h2': typeof LangDocsFrameworkComponentsH2Route
  '/$lang/docs/$framework/components/h3': typeof LangDocsFrameworkComponentsH3Route
  '/$lang/docs/$framework/components/h4': typeof LangDocsFrameworkComponentsH4Route
  '/$lang/docs/$framework/components/h5': typeof LangDocsFrameworkComponentsH5Route
  '/$lang/docs/$framework/components/h6': typeof LangDocsFrameworkComponentsH6Route
  '/$lang/docs/$framework/components/header': typeof LangDocsFrameworkComponentsHeaderRoute
  '/$lang/docs/$framework/components/input': typeof LangDocsFrameworkComponentsInputRoute
  '/$lang/docs/$framework/components/li': typeof LangDocsFrameworkComponentsLiRoute
  '/$lang/docs/$framework/components/navaccordion': typeof LangDocsFrameworkComponentsNavaccordionRoute
  '/$lang/docs/$framework/components/option': typeof LangDocsFrameworkComponentsOptionRoute
  '/$lang/docs/$framework/components/pager': typeof LangDocsFrameworkComponentsPagerRoute
  '/$lang/docs/$framework/components/pagers': typeof LangDocsFrameworkComponentsPagersRoute
  '/$lang/docs/$framework/components/select': typeof LangDocsFrameworkComponentsSelectRoute
  '/$lang/docs/$framework/components/ul': typeof LangDocsFrameworkComponentsUlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/docs'
    | '/$lang/test'
    | '/$lang/'
    | '/$lang/docs/$framework'
    | '/$lang/docs/'
    | '/$lang/docs/$framework/installation'
    | '/$lang/docs/$framework/overview'
    | '/$lang/docs/$framework/components/anchor'
    | '/$lang/docs/$framework/components/badge'
    | '/$lang/docs/$framework/components/breadcrumb'
    | '/$lang/docs/$framework/components/button'
    | '/$lang/docs/$framework/components/codeblock'
    | '/$lang/docs/$framework/components/divider'
    | '/$lang/docs/$framework/components/error'
    | '/$lang/docs/$framework/components/h1'
    | '/$lang/docs/$framework/components/h2'
    | '/$lang/docs/$framework/components/h3'
    | '/$lang/docs/$framework/components/h4'
    | '/$lang/docs/$framework/components/h5'
    | '/$lang/docs/$framework/components/h6'
    | '/$lang/docs/$framework/components/header'
    | '/$lang/docs/$framework/components/input'
    | '/$lang/docs/$framework/components/li'
    | '/$lang/docs/$framework/components/navaccordion'
    | '/$lang/docs/$framework/components/option'
    | '/$lang/docs/$framework/components/pager'
    | '/$lang/docs/$framework/components/pagers'
    | '/$lang/docs/$framework/components/select'
    | '/$lang/docs/$framework/components/ul'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/test'
    | '/$lang'
    | '/$lang/docs/$framework'
    | '/$lang/docs'
    | '/$lang/docs/$framework/installation'
    | '/$lang/docs/$framework/overview'
    | '/$lang/docs/$framework/components/anchor'
    | '/$lang/docs/$framework/components/badge'
    | '/$lang/docs/$framework/components/breadcrumb'
    | '/$lang/docs/$framework/components/button'
    | '/$lang/docs/$framework/components/codeblock'
    | '/$lang/docs/$framework/components/divider'
    | '/$lang/docs/$framework/components/error'
    | '/$lang/docs/$framework/components/h1'
    | '/$lang/docs/$framework/components/h2'
    | '/$lang/docs/$framework/components/h3'
    | '/$lang/docs/$framework/components/h4'
    | '/$lang/docs/$framework/components/h5'
    | '/$lang/docs/$framework/components/h6'
    | '/$lang/docs/$framework/components/header'
    | '/$lang/docs/$framework/components/input'
    | '/$lang/docs/$framework/components/li'
    | '/$lang/docs/$framework/components/navaccordion'
    | '/$lang/docs/$framework/components/option'
    | '/$lang/docs/$framework/components/pager'
    | '/$lang/docs/$framework/components/pagers'
    | '/$lang/docs/$framework/components/select'
    | '/$lang/docs/$framework/components/ul'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/docs'
    | '/$lang/test'
    | '/$lang/'
    | '/$lang/docs/$framework'
    | '/$lang/docs/'
    | '/$lang/docs/$framework/installation'
    | '/$lang/docs/$framework/overview'
    | '/$lang/docs/$framework/components/anchor'
    | '/$lang/docs/$framework/components/badge'
    | '/$lang/docs/$framework/components/breadcrumb'
    | '/$lang/docs/$framework/components/button'
    | '/$lang/docs/$framework/components/codeblock'
    | '/$lang/docs/$framework/components/divider'
    | '/$lang/docs/$framework/components/error'
    | '/$lang/docs/$framework/components/h1'
    | '/$lang/docs/$framework/components/h2'
    | '/$lang/docs/$framework/components/h3'
    | '/$lang/docs/$framework/components/h4'
    | '/$lang/docs/$framework/components/h5'
    | '/$lang/docs/$framework/components/h6'
    | '/$lang/docs/$framework/components/header'
    | '/$lang/docs/$framework/components/input'
    | '/$lang/docs/$framework/components/li'
    | '/$lang/docs/$framework/components/navaccordion'
    | '/$lang/docs/$framework/components/option'
    | '/$lang/docs/$framework/components/pager'
    | '/$lang/docs/$framework/components/pagers'
    | '/$lang/docs/$framework/components/select'
    | '/$lang/docs/$framework/components/ul'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/heartbeat': typeof ApiHeartbeatServerRoute
  '/api/page-info': typeof ApiPageInfoServerRoute
}
export interface FileServerRoutesByTo {
  '/api/heartbeat': typeof ApiHeartbeatServerRoute
  '/api/page-info': typeof ApiPageInfoServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/heartbeat': typeof ApiHeartbeatServerRoute
  '/api/page-info': typeof ApiPageInfoServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/heartbeat' | '/api/page-info'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/heartbeat' | '/api/page-info'
  id: '__root__' | '/api/heartbeat' | '/api/page-info'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiHeartbeatServerRoute: typeof ApiHeartbeatServerRoute
  ApiPageInfoServerRoute: typeof ApiPageInfoServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/test': {
      id: '/$lang/test'
      path: '/test'
      fullPath: '/$lang/test'
      preLoaderRoute: typeof LangTestRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/docs': {
      id: '/$lang/docs'
      path: '/docs'
      fullPath: '/$lang/docs'
      preLoaderRoute: typeof LangDocsRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/docs/': {
      id: '/$lang/docs/'
      path: '/'
      fullPath: '/$lang/docs/'
      preLoaderRoute: typeof LangDocsIndexRouteImport
      parentRoute: typeof LangDocsRouteRoute
    }
    '/$lang/docs/$framework': {
      id: '/$lang/docs/$framework'
      path: '/$framework'
      fullPath: '/$lang/docs/$framework'
      preLoaderRoute: typeof LangDocsFrameworkRouteRouteImport
      parentRoute: typeof LangDocsRouteRoute
    }
    '/$lang/docs/$framework/overview': {
      id: '/$lang/docs/$framework/overview'
      path: '/overview'
      fullPath: '/$lang/docs/$framework/overview'
      preLoaderRoute: typeof LangDocsFrameworkOverviewRouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/installation': {
      id: '/$lang/docs/$framework/installation'
      path: '/installation'
      fullPath: '/$lang/docs/$framework/installation'
      preLoaderRoute: typeof LangDocsFrameworkInstallationRouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/ul': {
      id: '/$lang/docs/$framework/components/ul'
      path: '/components/ul'
      fullPath: '/$lang/docs/$framework/components/ul'
      preLoaderRoute: typeof LangDocsFrameworkComponentsUlRouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/select': {
      id: '/$lang/docs/$framework/components/select'
      path: '/components/select'
      fullPath: '/$lang/docs/$framework/components/select'
      preLoaderRoute: typeof LangDocsFrameworkComponentsSelectRouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/pagers': {
      id: '/$lang/docs/$framework/components/pagers'
      path: '/components/pagers'
      fullPath: '/$lang/docs/$framework/components/pagers'
      preLoaderRoute: typeof LangDocsFrameworkComponentsPagersRouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/pager': {
      id: '/$lang/docs/$framework/components/pager'
      path: '/components/pager'
      fullPath: '/$lang/docs/$framework/components/pager'
      preLoaderRoute: typeof LangDocsFrameworkComponentsPagerRouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/option': {
      id: '/$lang/docs/$framework/components/option'
      path: '/components/option'
      fullPath: '/$lang/docs/$framework/components/option'
      preLoaderRoute: typeof LangDocsFrameworkComponentsOptionRouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/navaccordion': {
      id: '/$lang/docs/$framework/components/navaccordion'
      path: '/components/navaccordion'
      fullPath: '/$lang/docs/$framework/components/navaccordion'
      preLoaderRoute: typeof LangDocsFrameworkComponentsNavaccordionRouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/li': {
      id: '/$lang/docs/$framework/components/li'
      path: '/components/li'
      fullPath: '/$lang/docs/$framework/components/li'
      preLoaderRoute: typeof LangDocsFrameworkComponentsLiRouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/input': {
      id: '/$lang/docs/$framework/components/input'
      path: '/components/input'
      fullPath: '/$lang/docs/$framework/components/input'
      preLoaderRoute: typeof LangDocsFrameworkComponentsInputRouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/header': {
      id: '/$lang/docs/$framework/components/header'
      path: '/components/header'
      fullPath: '/$lang/docs/$framework/components/header'
      preLoaderRoute: typeof LangDocsFrameworkComponentsHeaderRouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/h6': {
      id: '/$lang/docs/$framework/components/h6'
      path: '/components/h6'
      fullPath: '/$lang/docs/$framework/components/h6'
      preLoaderRoute: typeof LangDocsFrameworkComponentsH6RouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/h5': {
      id: '/$lang/docs/$framework/components/h5'
      path: '/components/h5'
      fullPath: '/$lang/docs/$framework/components/h5'
      preLoaderRoute: typeof LangDocsFrameworkComponentsH5RouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/h4': {
      id: '/$lang/docs/$framework/components/h4'
      path: '/components/h4'
      fullPath: '/$lang/docs/$framework/components/h4'
      preLoaderRoute: typeof LangDocsFrameworkComponentsH4RouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/h3': {
      id: '/$lang/docs/$framework/components/h3'
      path: '/components/h3'
      fullPath: '/$lang/docs/$framework/components/h3'
      preLoaderRoute: typeof LangDocsFrameworkComponentsH3RouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/h2': {
      id: '/$lang/docs/$framework/components/h2'
      path: '/components/h2'
      fullPath: '/$lang/docs/$framework/components/h2'
      preLoaderRoute: typeof LangDocsFrameworkComponentsH2RouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/h1': {
      id: '/$lang/docs/$framework/components/h1'
      path: '/components/h1'
      fullPath: '/$lang/docs/$framework/components/h1'
      preLoaderRoute: typeof LangDocsFrameworkComponentsH1RouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/error': {
      id: '/$lang/docs/$framework/components/error'
      path: '/components/error'
      fullPath: '/$lang/docs/$framework/components/error'
      preLoaderRoute: typeof LangDocsFrameworkComponentsErrorRouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/divider': {
      id: '/$lang/docs/$framework/components/divider'
      path: '/components/divider'
      fullPath: '/$lang/docs/$framework/components/divider'
      preLoaderRoute: typeof LangDocsFrameworkComponentsDividerRouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/codeblock': {
      id: '/$lang/docs/$framework/components/codeblock'
      path: '/components/codeblock'
      fullPath: '/$lang/docs/$framework/components/codeblock'
      preLoaderRoute: typeof LangDocsFrameworkComponentsCodeblockRouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/button': {
      id: '/$lang/docs/$framework/components/button'
      path: '/components/button'
      fullPath: '/$lang/docs/$framework/components/button'
      preLoaderRoute: typeof LangDocsFrameworkComponentsButtonRouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/breadcrumb': {
      id: '/$lang/docs/$framework/components/breadcrumb'
      path: '/components/breadcrumb'
      fullPath: '/$lang/docs/$framework/components/breadcrumb'
      preLoaderRoute: typeof LangDocsFrameworkComponentsBreadcrumbRouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/badge': {
      id: '/$lang/docs/$framework/components/badge'
      path: '/components/badge'
      fullPath: '/$lang/docs/$framework/components/badge'
      preLoaderRoute: typeof LangDocsFrameworkComponentsBadgeRouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
    '/$lang/docs/$framework/components/anchor': {
      id: '/$lang/docs/$framework/components/anchor'
      path: '/components/anchor'
      fullPath: '/$lang/docs/$framework/components/anchor'
      preLoaderRoute: typeof LangDocsFrameworkComponentsAnchorRouteImport
      parentRoute: typeof LangDocsFrameworkRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/page-info': {
      id: '/api/page-info'
      path: '/api/page-info'
      fullPath: '/api/page-info'
      preLoaderRoute: typeof ApiPageInfoServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/heartbeat': {
      id: '/api/heartbeat'
      path: '/api/heartbeat'
      fullPath: '/api/heartbeat'
      preLoaderRoute: typeof ApiHeartbeatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface LangDocsFrameworkRouteRouteChildren {
  LangDocsFrameworkInstallationRoute: typeof LangDocsFrameworkInstallationRoute
  LangDocsFrameworkOverviewRoute: typeof LangDocsFrameworkOverviewRoute
  LangDocsFrameworkComponentsAnchorRoute: typeof LangDocsFrameworkComponentsAnchorRoute
  LangDocsFrameworkComponentsBadgeRoute: typeof LangDocsFrameworkComponentsBadgeRoute
  LangDocsFrameworkComponentsBreadcrumbRoute: typeof LangDocsFrameworkComponentsBreadcrumbRoute
  LangDocsFrameworkComponentsButtonRoute: typeof LangDocsFrameworkComponentsButtonRoute
  LangDocsFrameworkComponentsCodeblockRoute: typeof LangDocsFrameworkComponentsCodeblockRoute
  LangDocsFrameworkComponentsDividerRoute: typeof LangDocsFrameworkComponentsDividerRoute
  LangDocsFrameworkComponentsErrorRoute: typeof LangDocsFrameworkComponentsErrorRoute
  LangDocsFrameworkComponentsH1Route: typeof LangDocsFrameworkComponentsH1Route
  LangDocsFrameworkComponentsH2Route: typeof LangDocsFrameworkComponentsH2Route
  LangDocsFrameworkComponentsH3Route: typeof LangDocsFrameworkComponentsH3Route
  LangDocsFrameworkComponentsH4Route: typeof LangDocsFrameworkComponentsH4Route
  LangDocsFrameworkComponentsH5Route: typeof LangDocsFrameworkComponentsH5Route
  LangDocsFrameworkComponentsH6Route: typeof LangDocsFrameworkComponentsH6Route
  LangDocsFrameworkComponentsHeaderRoute: typeof LangDocsFrameworkComponentsHeaderRoute
  LangDocsFrameworkComponentsInputRoute: typeof LangDocsFrameworkComponentsInputRoute
  LangDocsFrameworkComponentsLiRoute: typeof LangDocsFrameworkComponentsLiRoute
  LangDocsFrameworkComponentsNavaccordionRoute: typeof LangDocsFrameworkComponentsNavaccordionRoute
  LangDocsFrameworkComponentsOptionRoute: typeof LangDocsFrameworkComponentsOptionRoute
  LangDocsFrameworkComponentsPagerRoute: typeof LangDocsFrameworkComponentsPagerRoute
  LangDocsFrameworkComponentsPagersRoute: typeof LangDocsFrameworkComponentsPagersRoute
  LangDocsFrameworkComponentsSelectRoute: typeof LangDocsFrameworkComponentsSelectRoute
  LangDocsFrameworkComponentsUlRoute: typeof LangDocsFrameworkComponentsUlRoute
}

const LangDocsFrameworkRouteRouteChildren: LangDocsFrameworkRouteRouteChildren =
  {
    LangDocsFrameworkInstallationRoute: LangDocsFrameworkInstallationRoute,
    LangDocsFrameworkOverviewRoute: LangDocsFrameworkOverviewRoute,
    LangDocsFrameworkComponentsAnchorRoute:
      LangDocsFrameworkComponentsAnchorRoute,
    LangDocsFrameworkComponentsBadgeRoute:
      LangDocsFrameworkComponentsBadgeRoute,
    LangDocsFrameworkComponentsBreadcrumbRoute:
      LangDocsFrameworkComponentsBreadcrumbRoute,
    LangDocsFrameworkComponentsButtonRoute:
      LangDocsFrameworkComponentsButtonRoute,
    LangDocsFrameworkComponentsCodeblockRoute:
      LangDocsFrameworkComponentsCodeblockRoute,
    LangDocsFrameworkComponentsDividerRoute:
      LangDocsFrameworkComponentsDividerRoute,
    LangDocsFrameworkComponentsErrorRoute:
      LangDocsFrameworkComponentsErrorRoute,
    LangDocsFrameworkComponentsH1Route: LangDocsFrameworkComponentsH1Route,
    LangDocsFrameworkComponentsH2Route: LangDocsFrameworkComponentsH2Route,
    LangDocsFrameworkComponentsH3Route: LangDocsFrameworkComponentsH3Route,
    LangDocsFrameworkComponentsH4Route: LangDocsFrameworkComponentsH4Route,
    LangDocsFrameworkComponentsH5Route: LangDocsFrameworkComponentsH5Route,
    LangDocsFrameworkComponentsH6Route: LangDocsFrameworkComponentsH6Route,
    LangDocsFrameworkComponentsHeaderRoute:
      LangDocsFrameworkComponentsHeaderRoute,
    LangDocsFrameworkComponentsInputRoute:
      LangDocsFrameworkComponentsInputRoute,
    LangDocsFrameworkComponentsLiRoute: LangDocsFrameworkComponentsLiRoute,
    LangDocsFrameworkComponentsNavaccordionRoute:
      LangDocsFrameworkComponentsNavaccordionRoute,
    LangDocsFrameworkComponentsOptionRoute:
      LangDocsFrameworkComponentsOptionRoute,
    LangDocsFrameworkComponentsPagerRoute:
      LangDocsFrameworkComponentsPagerRoute,
    LangDocsFrameworkComponentsPagersRoute:
      LangDocsFrameworkComponentsPagersRoute,
    LangDocsFrameworkComponentsSelectRoute:
      LangDocsFrameworkComponentsSelectRoute,
    LangDocsFrameworkComponentsUlRoute: LangDocsFrameworkComponentsUlRoute,
  }

const LangDocsFrameworkRouteRouteWithChildren =
  LangDocsFrameworkRouteRoute._addFileChildren(
    LangDocsFrameworkRouteRouteChildren,
  )

interface LangDocsRouteRouteChildren {
  LangDocsFrameworkRouteRoute: typeof LangDocsFrameworkRouteRouteWithChildren
  LangDocsIndexRoute: typeof LangDocsIndexRoute
}

const LangDocsRouteRouteChildren: LangDocsRouteRouteChildren = {
  LangDocsFrameworkRouteRoute: LangDocsFrameworkRouteRouteWithChildren,
  LangDocsIndexRoute: LangDocsIndexRoute,
}

const LangDocsRouteRouteWithChildren = LangDocsRouteRoute._addFileChildren(
  LangDocsRouteRouteChildren,
)

interface LangRouteRouteChildren {
  LangDocsRouteRoute: typeof LangDocsRouteRouteWithChildren
  LangTestRouteRoute: typeof LangTestRouteRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangDocsRouteRoute: LangDocsRouteRouteWithChildren,
  LangTestRouteRoute: LangTestRouteRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiHeartbeatServerRoute: ApiHeartbeatServerRoute,
  ApiPageInfoServerRoute: ApiPageInfoServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
