name = "nuco"
main = "./build/server/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-11-13"
upload_source_maps = true

[observability.logs]
enabled = true

[assets]
directory = "./build/client"
