import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@nuco/variable/css";

import { Poppins } from "next/font/google";
import { defineColorScheme } from "@nuco/variable";
import { ColorScheme } from "@/app/components/ColorScheme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const PoppinsFont = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ColorScheme />
      <body className={`${geistSans.variable} ${geistMono.variable} ${PoppinsFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
