name: PR Tests - reactivity & runtime

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'packages/reactivity/**'
      - 'packages/runtime/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Read package.json to get volta config
      - name: Get Volta versions
        id: volta
        run: |
          NODE_VERSION=$(node -p "require('./package.json').volta.node")
          PNPM_VERSION=$(node -p "require('./package.json').volta.pnpm")
          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_OUTPUT
          echo "PNPM_VERSION=$PNPM_VERSION" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.volta.outputs.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ steps.volta.outputs.PNPM_VERSION }}

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm build

      # Run tests based on changed packages
      - name: Detect changed packages
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            reactivity:
              - 'packages/reactivity/**'
            runtime:
              - 'packages/runtime/**'

      # Run tests for changed packages
      - name: Run tests for changed packages
        shell: bash
        run: |
          if [[ "${{ steps.filter.outputs.reactivity }}" == "true" ]]; then
            echo "Running tests for reactivity package..."
            pnpm p:rtv test
          fi

          if [[ "${{ steps.filter.outputs.runtime }}" == "true" ]]; then
            echo "Running tests for runtime package..."
            pnpm p:rt test
          fi
